### PR TITLE
Add Coding Guidelines and Directory Structure Documentation

### PR DESCRIPTION
**Pull request by xlai**
Description:

This pull request introduces two essential documents to our project:

- coding_guidelines.md: A detailed guide to the coding conventions for R to be followed by all developers on the project. It ensures consistency and clarity across the codebase.
- directory_structure.md: An explanation of the project's directory structure, outlining where specific files and modules are located.

Motivation:

With multiple developers working on different aspects of the application, having clear guidelines and an organized structure is crucial. These documents will make the project more maintainable and accessible, allowing for smoother collaboration. 

Testing:

Ensure that all team members have access to and understand the documents.

Related Issue:
See #7 for details.

### CODE REVIEW

**Review by eduardo-vie — APPROVED** [review]
Thanks for adding these.

I have no qualms besides the two-space indent thing. :)

**Comment by xlai** [comment]
> Thanks for adding these.
> 
> I have no qualms besides the two-space indent thing. :)

That's great. I've shown you how to adjust the tab size to be equivalent of 2 spaces. Hope that solves the problem.

**Review by jakeholton — APPROVED** [review]
No comments.

**Review by sdennett20 — APPROVED** [review]
Happy with the directory structure and coding guidelines. Thanks for the addition of these!

**Pull request merged**
